version: "3.7"
services:
    data-prepper:
    restart: unless-stopped
    container_name: data-prepper
    build:
      args:
        DATA_PREPPER_VERSION: "2.0.0-SNAPSHOT"
      context: ../../..
      dockerfile: examples/dev/trace-analytics-sample-app/Dockerfile
    working_dir: /usr/share/data-prepper/
    command: sh data-prepper-wait-for-opensearch-and-start.sh
    volumes:
      - ./resources/data-prepper-wait-for-opensearch-and-start.sh:/usr/share/data-prepper/data-prepper-wait-for-opensearch-and-start.sh
      - ./resources/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./resources/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
      - ../../../shared-config/log4j2.properties:/usr/share/data-prepper/config/log4j.properties
      - ../../demo/root-ca.pem:/usr/share/data-prepper/root-ca.pem
      - ../../demo/test_keystore.p12:/usr/share/data-prepper/test_keystore.p12
      - ../../demo/demo-data-prepper.crt:/usr/share/data-prepper/demo-data-prepper.crt
      - ../../demo/demo-data-prepper.key:/usr/share/data-prepper/demo-data-prepper.key
    ports:
      - "4900:4900" # DataPrepperServer port
      - "21890:21890" # OTelTraceSource port
    networks:
      my_network:

  otel-collector:
    restart: unless-stopped
    dns: 10.10.1.1
    image: otel/opentelemetry-collector:0.24.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./opentelemetry-collector/otel-collector-config.yml:/etc/otel-collector-config.yml
      - ../../demo/demo-data-prepper.crt:/etc/demo-data-prepper.crt
    ports:
      - "55680:55680"
    depends_on:
      - data-prepper
    networks:
      - my_network

  mysql:
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - my_network
  sample-app:
    restart: unless-stopped
    build:
      context: ../../trace-analytics-sample-app/sample-app
      dockerfile: Dockerfile
    ports:
      - "8082:8082" # inventory
      - "8083:8083" # database
      - "8084:8084" # payment
      - "8085:8085" # auth
      - "8086:8086" # recommendation
      - "8087:8087" # analytics-service
      - "8088:8088" # order
      - "8089:8089" # client-dashboard
    environment:
      - OTEL_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:55680
      - OTEL_RESOURCE_ATTRIBUTES=service.name=analytics-service
      - OTLP=otel-collector
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - WAIT_HOSTS=otel-collector:55680, mysql:3306
    depends_on:
      - otel-collector
      - mysql
    networks:
      - my_network
